[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
projectsetup = "Ep6Cgue7MrTCpTqFhCZfF9yMPA8VA2CJg1u5pmuJ6yQ9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yash/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
